brew install glew
brew install sdl2
brew install glfw
brew install mesa-glu
brew install allegro
brew install sfml
brew install xz
brew install unicorn
brew install libarchive
brew install nginx
brew install geoip
brew install perl
brew install mcrypt